# Generated by Django 5.0.3 on 2024-05-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_course_available_spots_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, related_name='completed_by_students', to='registration.course'),
        ),
    ]
