# Generated by Django 5.0.3 on 2024-05-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_student_completed_courses'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentregistration',
            unique_together={('student', 'course')},
        ),
    ]
