# Generated by Django 5.0.3 on 2024-05-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
